### ISSUE TITLE
Users are unable to edit page properties when sluggi is installed since TYPO3 9.5.14: Missing UID

### ISSUE THREAD

**Issue by Schwuuuuup** [wazum/sluggi#19]
Hi,

We are using
- TYPO3 9.5.14 LTS
- sluggi from TER (1.8.3) and sluggi from Github (1.9.0)
- PHP 7.2.23 (cli) (built: Oct 17 2019 16:19:35) ( NTS )
- Apache/2.4.25 (Debian) 2019-10-13T15:43:54

With both versions we get an error since we updated from TYPO3 9.5.13.
Whenever a non-admin user tries to edit the page properties of any page, they get:

```
Wed, 19 Feb 2020 11:40:30 +0100 [CRITICAL]
request="729a2287d0a71"
component="TYPO3.CMS.Core.Error.DebugExceptionHandler":
Core: Exception handler (WEB):
Uncaught TYPO3 Exception: #1578950324: The given page record is invalid. Missing uid. |
RuntimeException thrown in file /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php in line 397.
Requested URL: https://rrzk.uni-koeln.de/typo3/index.php?route=%2Frecord%2Fedit&token=--AnonymizedToken--&edit%5Bpages%5D%5B12735%5D=edit&returnUrl=%2Ftypo3%2Findex.php%3Froute%3D%252Fweb%252Flayout%252F%26token%3D482f7493fcc3d794a7e664ba5293c2421e032a94%26id%3D12735 -
{"TYPO3_MODE":"BE","exception":"RuntimeException: The given page record is invalid. Missing uid. in /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php:397
Stack trace:
#0 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php(632): 
TYPO3\\CMS\\Core\\Authentication\\BackendUserAuthentication->isInWebMount(Array)
#1 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php(369): 
TYPO3\\CMS\\Core\\Authentication\\BackendUserAuthentication->calcPerms(Array)
#2 /var/www/html/typo3conf/ext/sluggi/Classes/Helper/PermissionHelper.php(73): 
TYPO3\\CMS\\Core\\Authentication\\BackendUserAuthentication->doesUserHaveAccess(Array, 2)
#3 /var/www/html/typo3conf/ext/sluggi/Classes/Backend/Form/InputSlugElement.php(44): 
Wazum\\Sluggi\\Helper\\PermissionHelper::getTopmostAccessiblePage(12735)
#4 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/SingleFieldContainer.php(180): 
Wazum\\Sluggi\\Backend\\Form\\InputSlugElement->render()
#5 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php(223): 
TYPO3\\CMS\\Backend\\Form\\Container\\SingleFieldContainer->render()
#6 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php(118): 
TYPO3\\CMS\\Backend\\Form\\Container\\PaletteAndSingleContainer->createPaletteContentArray('title')
#7 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/TabsContainer.php(86): 
TYPO3\\CMS\\Backend\\Form\\Container\\PaletteAndSingleContainer->render()
#8 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/FullRecordContainer.php(83): 
TYPO3\\CMS\\Backend\\Form\\Container\\TabsContainer->render()
#9 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Form/Container/OuterWrapContainer.php(55): 
TYPO3\\CMS\\Backend\\Form\\Container\\FullRecordContainer->render()
#10 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Controller/EditDocumentController.php(1369): 
TYPO3\\CMS\\Backend\\Form\\Container\\OuterWrapContainer->render()
#11 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Controller/EditDocumentController.php(1198): 
TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->makeEditForm()
#12 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Controller/EditDocumentController.php(537): 
TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->main(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#13 [internal function]: 
TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->mainAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#14 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(87): 
call_user_func_array(Array,
 Array)
#15 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Http/RequestHandler.php(73): 
TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(TYPO3\\CMS\\Core\\Http\\Response))
#16 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(59): 
TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#17 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))
#18 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(39): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#19 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#20 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(45): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#21 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#22 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/LegacyBackendTemplateInitialization.php(42): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#23 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\LegacyBackendTemplateInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#24 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(70): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#25 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#26 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(72): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#27 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#28 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#29 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#30 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#31 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#32 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#33 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): 
TYPO3\\CMS\\Core\\Middleware\
ormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest),
 Object(class@anonymous))
#34 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): 
class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#35 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): 
TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#36 /var/www/html/typo3_src-9.5.14/typo3/sysext/backend/Classes/Http/Application.php(68): 
TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#37 /var/www/html/typo3_src-9.5.14/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): 
TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#38 /var/www/html/typo3_src-9.5.14/typo3/index.php(24): 
TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#39 /var/www/html/typo3_src-9.5.14/typo3/index.php(25): 
{closure}()
#40 {main}"}

```

**Comment by wazum** [comment]
Thanks for the report, I'll take a look at it tomorrow

**Comment by wazum** [comment]
@Schwuuuuup thanks for the report, please try with 1.9.1 I just tagged on github and packagist

**Comment by Schwuuuuup** [comment]
@wazum Wow, you are quick! We tested it, and the problem is gone on at least one of our TYPO3s further tests will come, but I'm sure it will be ok.
Thanks a lot!
